-- 商品テーブル
CREATE TABLE IF NOT EXISTS item (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255),
  price INT NOT NULL,
  taxRate INT NOT NULL DEFAULT 0,
  priceWithTax INT NOT NULL DEFAULT 0,
  vendor VARCHAR(255),
  PRIMARY KEY (id),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
